### PR TITLE
Style guide with useful tools

### PR DESCRIPTION
**Pull request by pavangudiwada**
@verma-kunal Take a look.

### CODE REVIEW

**Review by dipankardas011 — APPROVED** [review]
LGTM @pavangudiwada  😄

**Comment by verma-kunal** [comment]
hey @pavangudiwada , can we also add a contact section at the end of the doc, so that ppl can reach out to you with any queries!?

**Comment by pavangudiwada** [comment]
@verma-kunal Let's not do that right now...? :smile:

**Comment by verma-kunal** [comment]
> @verma-kunal Let's not do that right now...? :smile: 

Sure! I understand.

**Comment by verma-kunal** [comment]
i think this looks good as v1 for the Style Guide! We'll keep improving it as time goes!
Thanks for creating this @pavangudiwada and for reviewing @dipankardas011

**Pull request merged**
