### PR TITLE
Install Kubernetes on MacBook Pro (M series) using kubeadm

### LINKED ISSUE #9: Install Kubernetes on MacBook Pro (M series) using kubeadm
Hi,
I would like to write a step by step tutorial on how to set up a 3 node Kubernetes cluster on a MacBook Pro laptop running on **Apple silicon chips (M series)**. VirtualBox does not have a GA release for M series laptops (only developer previews are present). As such I believe it is important that readers would use a **compatible virtualization solution** to provision their VMs.
My post uses [Canonical's multipass](https://multipass.run/).

My solution is resilient to laptop restarts and ensures that the VMs are allocated the same IP addresses even after restarts, which is very important for the Kubernetes cluster to function in the long run.

This will be great for readers who would like to setup and manage their own Kubernetes cluster locally, without relying only on minikube, kind, K3s or MicroK8s.

Awaiting your feedback if this blog post would be beneficial for KubeSimplify.

### PR DESCRIPTION
**Pull request by adityasamant25**
Fixes #9 

This PR contains the draft for a new contribution to the [Kubesimplify Blog](https://blog.kubesimplify.com/).

Kindly review it. I am available for any changes or modifications that seem necessary.

Awaiting feedback for the next steps.

Kind Regards,
Aditya

### CODE REVIEW

**Comment by verma-kunal** [comment]
Thanks for the PR @adityasamant25 ! Will review this asap & get back to you

**Comment by verma-kunal** [comment]
Hey @adityasamant25 , thank you so much for the blog submission! It's very well structured and detailed.

Two things remaining:
- can you pls add a section of `Resources` at the end and give links to the resources being used + some additional ones such as docs/blogs/videos etc, for viewer's reference.
- you may proceed to create a cover image for this. ideal size would be `1600 x 840px` (for Hashnode cover)

Lemme know once these are done & then we are ready to publish!

**Comment by adityasamant25** [comment]
Hi @verma-kunal, sure. Let me work on that and get back to you.

**Comment by adityasamant25** [comment]
Hi @verma-kunal,
I've added a section for Resources. I've added a cover image as well.

Please take a look. Awaiting your feedback.

Kind Regards,
Aditya.

**Comment by verma-kunal** [comment]
Thanks for adding! A small nit-picking - adding the blog title on the cover would look good & easily navigable. 

Lastly, pls provide your email & i'll add you as a `contributor` to our hashnode blog & then you are free to add your article there!

**Comment by verma-kunal** [comment]
Taking this conversation to our discord server from here on!

**Pull request merged**
